### ISSUE TITLE
SQL STM -  ToDO

### ISSUE THREAD

**Issue by HejlesenCPH** [uiop860/Flow1BankOpgave#16]
Withdraw
- [x]  Display current balance 
- [x] Whithdraw amount from account 
- [x] Display current balance 

Deposit 
- [x] Display current balance 
- [x] Deposit amount from balance 
- [x] Display current balance

Transaction
- [x] Display amount 
- [x] whitdraw amount from one account 
- [x]  Deposit on another account 
- [x] Display current balance
